正向传播用数组表示

In [40]:
#得到z
import numpy as np
x = np.array([[-11,2,3],[-7,0,6],[7,0,9]])
w = np.array([[4],[6],[6]])
b = 1
z = np.dot(w.transpose(),x)+b
z = z[0]
print(z)

#得到a
a = 1/(1+np.exp(z*(-1)))
print(a)

#设置y
y = np.array([1,0,1])
print(y)
#求J
# h = sum(a-y)/3
# print(sum)

#求dz = [a^1-y^1......]
dz = (a-y).reshape(3,1)
dw = np.dot(x,dz)/3
print(dw)


[-43   9 103]
[2.11513104e-19 9.99876605e-01 1.00000000e+00]
[1 0 1]
[[ 4.33325107]
 [ 2.33333333]
 [-2.33333333]]
